server:
  error:
    include-stacktrace: on_param
spring:
  datasource:
    url: jdbc:${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus

info:
  app: AnimeApi
  website: https://andersonleite.dev.br
  github: https://github.com/andersonleite1/AnimeApi