name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt-openjdk'

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests and generate code coverage report
        run: mvn test

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v3
        with:
          # Specify the location of your coverage report if different
          file: target/site/jacoco/jacoco.xml
          # Optional: Specify the Codecov token (you can use repository secrets for this)
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Report Coverage
        run: curl -s https://codecov.io/bash | bash
